name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: "ap-south-1"
  DOCKER_IMAGE_NAME: "krishnamoorthy1/particle41"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: DOCKERHUB_USERNAME 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  
        password: ${{ secrets.DOCKERHUB_TOKEN }}    

    - name: Build and Push Docker image
      id: docker_build
      run: |
        TAG=${GITHUB_SHA::7}
        docker build -t ${{ env.DOCKER_IMAGE_NAME }}:$TAG -f app/Dockerfile app/
        docker push ${{ env.DOCKER_IMAGE_NAME }}:$TAG
        echo "image_tag=$TAG" >> $GITHUB_OUTPUT

    - name: Update Terraform variables
      run: |
        TAG=${{ steps.docker_build.outputs.image_tag }}
        sed -i "s|container_image *=.*|container_image = \"${{ env.DOCKER_IMAGE_NAME }}:$TAG\"|" terraform/terraform.tfvars
        sed -i "s|region *=.*|region = \"${{ env.AWS_REGION }}\"|" terraform/terraform.tfvars
