name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
permissions:
  contents: write


jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: DOCKERHUB_USERNAME 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Needed to get git history for pushing changes

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  
        password: ${{ secrets.DOCKERHUB_TOKEN }}    

    - name: Build and Push Docker image
      id: docker_build
      run: |
        TAG=${GITHUB_SHA::7}
        docker build -t ${{ secrets.DOCKER_REPO }}:$TAG -f app/Dockerfile app/
        docker push ${{ secrets.DOCKER_REPO }}:$TAG
        echo "image_tag=$TAG" >> $GITHUB_OUTPUT

    - name: Update Terraform variables
      run: |
        TAG=${{ steps.docker_build.outputs.image_tag }}
        sed -i "s|container_image *=.*|container_image = \"${{ secrets.DOCKER_REPO }}:$TAG\"|" terraform/terraform.tfvars
        sed -i "s|region *=.*|region = \"${{ secrets.AWS_REGION }}\"|" terraform/terraform.tfvars

    - name: Commit and push changes
      run: |
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git add terraform/terraform.tfvars
        git commit -m "Update container_image to ${{ secrets.DOCKER_REPO }}:${{ steps.docker_build.outputs.image_tag }}"
        git push

      
  terraform-deploy:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: DOCKERHUB_USERNAME
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve

   
